# Generated by Django 5.0.4 on 2024-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='career_file',
            field=models.FileField(default=1, upload_to='img/career/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3+ Year', '3+ Year')], default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='join',
            field=models.CharField(choices=[('Right now', 'Right now'), ('In a few week', 'In a few week'), ('In a few month', 'In a few month'), ('No Sure', 'No Sure')], default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(choices=[('Network Engineer', 'Network Engineer'), ('Sale Excutive', 'Sale Excutive')], max_length=50),
        ),
    ]
