# Generated by Django 5.0.4 on 2024-06-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_career_career_file_career_experience_career_join_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='description',
            field=models.TextField(default=5, max_length=10000),
            preserve_default=False,
        ),
    ]
