# Generated by Django 5.0.4 on 2024-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_remove_career_career_file_remove_career_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1 Year', '1 Year'), ('2 Year', '2 Year'), ('3+ Year', '3+ Year')], default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='join',
            field=models.CharField(choices=[('Right now', 'Right now'), ('In a few week', 'In a few week'), ('In a few month', 'In a few month'), ('No Sure', 'No Sure')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='position',
            field=models.CharField(choices=[('Network Engineer', 'Network Engineer'), ('Sale Excutive', 'Sale Excutive')], default=4, max_length=50),
            preserve_default=False,
        ),
    ]
