# Generated by Django 5.0.4 on 2024-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_career_experience_career_join_career_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='career_file',
            field=models.FileField(default=1, upload_to='img/career/'),
            preserve_default=False,
        ),
    ]
