# Generated by Django 5.0.4 on 2024-06-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0006_career_career_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='career_file',
            field=models.FileField(upload_to=''),
        ),
    ]
