# Generated by Django 5.0.4 on 2024-06-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_alter_career_career_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='career_file',
        ),
        migrations.AddField(
            model_name='career',
            name='document',
            field=models.FileField(default=3, upload_to='career/'),
            preserve_default=False,
        ),
    ]
