# Generated by Django 5.0.4 on 2024-06-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_alter_career_document_alter_career_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
