# Generated by Django 5.0.4 on 2024-06-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_remove_career_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
