# Generated by Django 5.0.4 on 2024-06-13 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0012_alter_career_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='document',
            field=models.FileField(default=2, upload_to='img/career/'),
            preserve_default=False,
        ),
    ]
