# Generated by Django 5.0.4 on 2024-06-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0016_alter_career_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='img/career/'),
        ),
    ]
